# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CMDP
     A QGIS plugin
     QGIS plugin for importing and analysing CAMS data
     Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
def classFactory(iface):
    """
    This function is called by QGIS when it loads the plugin.
    :param iface: An interface instance that will be passed to our plugin
    :return: a CMDP instance
    """

    # Import the CMDP class from CMDP.py
    from .CMDP import CMDP
    # Create and return an instance of the CMDP class
    return CMDP(iface)
